### ISSUE TITLE
Numpy problem

### ISSUE THREAD

**Issue by francicco** [seqcode/allo#2]
Hi,

I was trying to test `allo`, but I came up with this error?

```
/user/work/tk19812/software/allo/allo_venv/bin/allo:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('bio-allo==1.1.2')

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/user/work/tk19812/software/allo/allo_venv/bin/allo", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/user/work/tk19812/software/allo/Allo/allo", line 33, in <module>
    import Allo
  File "/user/work/tk19812/software/allo/Allo/__init__.py", line 1, in <module>
    from . import predictPeak
  File "/user/work/tk19812/software/allo/Allo/predictPeak.py", line 7, in <module>
    import tensorflow as tf
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/saved_model/builder_impl.py", line 26, in <module>
    from tensorflow.python.framework import dtypes
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/framework/dtypes.py", line 35, in <module>
    from tensorflow.tsl.python.lib.core import pywrap_ml_dtypes
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/user/work/tk19812/software/allo/allo_venv/bin/allo", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/user/work/tk19812/software/allo/Allo/allo", line 33, in <module>
    import Allo
  File "/user/work/tk19812/software/allo/Allo/__init__.py", line 1, in <module>
    from . import predictPeak
  File "/user/work/tk19812/software/allo/Allo/predictPeak.py", line 7, in <module>
    import tensorflow as tf
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/saved_model/builder_impl.py", line 26, in <module>
    from tensorflow.python.framework import dtypes
  File "/user/work/tk19812/software/allo/allo_venv/lib64/python3.11/site-packages/tensorflow/python/framework/dtypes.py", line 37, in <module>
    _np_bfloat16 = pywrap_ml_dtypes.bfloat16()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
```

What are the version of python module that are required?
Can you help me please?

Cheers
F

**Comment by anmorrissey** [comment]
This was most likely an issue with Tensorflow. It is extremely finicky with version compatibility. I have updated the models to Tensorflow 2.17 as of the Allo release today (1.2.0). Let me know if the newest version works for you. Until bioconda updates (can take a couple days sometimes), you may have to install through pip.
